name: Codecov
description: Runs the codecov bash reporter over your code
author: https://github.com/joscha
requirements:
  - bash
  - docker
  - gpg
configuration:
  properties:
    args:
      type: array
    skip_on_fail:
      type: boolean
    uploader_version:
      type: string
    tmp_dir:
      type: string
  additionalProperties: false
