steps:
  - label: "🤡 :hammer:"
    plugins:
      - docker-compose#v5.4.0:
          run: tests
  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.1.0:
          id: joscha/codecov
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files: hooks/**
