#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Reads a list from plugin config into a global result array
# Returns success if values were read
plugin_read_list_into_result() {
  result=()

  for prefix in "$@" ; do
    local i=0
    local parameter="${prefix}_${i}"

    if [[ -n "${!prefix:-}" ]] ; then
      echo "🚨 Plugin received a string for $prefix, expected an array" >&2
      exit 1
    fi

    while [[ -n "${!parameter:-}" ]]; do
      result+=("${!parameter}")
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  done

  [[ ${#result[@]} -gt 0 ]] || return 1
}

main() {
  if [[ "${BUILDKITE_PLUGIN_CODECOV_SKIP_ON_FAIL:-false}" =~ ^(true|on|1)$ ]] && [[ "${BUILDKITE_COMMAND_EXIT_STATUS}" -ne 0 ]]; then
    echo "Codecov upload is skipped because step failed with status ${BUILDKITE_COMMAND_EXIT_STATUS}"
    exit 0
  fi

  curl -s https://codecov.io/bash > codecov;

  CODECOV_VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2);
  CODECOV_SHA=$(sha1sum codecov)
  REMOTE_SHA=$(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/$CODECOV_VERSION/SHA1SUM)

  if [[ "${CODECOV_SHA}" != "${REMOTE_SHA}" ]]; then
    echo "Codecov bash script SHA verification has failed!"
    exit 0
  fi

  pushd "${BUILDKITE_BUILD_CHECKOUT_PATH}" >/dev/null

  local args=()
  local force_zero_exit="true" # by default this plugin never fails
  if plugin_read_list_into_result BUILDKITE_PLUGIN_CODECOV_ARGS ; then
    for arg in "${result[@]}" ; do
      args+=("${arg}")
      if [[ "${arg}" == "-Z" ]]; then
        force_zero_exit="false"
      fi
    done
  fi

  local ci_env
  ci_env=$(bash $DIR/../scripts/env)

  set +e
  local exit_code
  docker run \
      $ci_env \
      --label "com.buildkite.job-id=${BUILDKITE_JOB_ID}" \
      --workdir=/workdir \
      --volume=$(pwd):/workdir \
      --volume=${DIR}/codecov:/codecov \
      -it \
      --rm \
      buildpack-deps:jessie-scm \
      bash -c "bash /codecov ${args[*]:-}"
  exit_code="$?"
  set -e
  popd >/dev/null
  rm codecov

  if [[ "${force_zero_exit}" != "true" ]]; then
    exit "${exit_code}"
  fi
}

main "$@"
