#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Reads a list from plugin config into a global result array
# Returns success if values were read
plugin_read_list_into_result() {
  result=()

  for prefix in "$@" ; do
    local i=0
    local parameter="${prefix}_${i}"

    if [[ -n "${!prefix:-}" ]] ; then
      echo "🚨 Plugin received a string for $prefix, expected an array" >&2
      exit 1
    fi

    while [[ -n "${!parameter:-}" ]]; do
      result+=("${!parameter}")
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  done

  [[ ${#result[@]} -gt 0 ]] || return 1
}

main() {
  if [[ "${BUILDKITE_PLUGIN_CODECOV_SKIP_ON_FAIL:-false}" =~ ^(true|on|1)$ ]] && [[ "${BUILDKITE_COMMAND_EXIT_STATUS}" -ne 0 ]]; then
    echo "Codecov upload is skipped because step failed with status ${BUILDKITE_COMMAND_EXIT_STATUS}"
    exit 0
  fi

  mkdir "${DIR}/codecov-bash"
  pushd "${DIR}/codecov-bash">/dev/null
  curl -s -S --connect-timeout 10 --retry 3 --retry-delay 10 -o bash https://codecov.io/bash;
  curl -s -S --connect-timeout 10 --retry 3 --retry-delay 10 -o env https://codecov.io/env;
  codecov_version=$(grep 'VERSION=\".*\"' bash | cut -d'"' -f2);
  if ! curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${codecov_version}/SHA1SUM" | sha1sum -c - > /dev/null; then
    echo "Codecov SHA verification has failed!"
    exit 1
  fi
  popd >/dev/null

  pushd "${BUILDKITE_BUILD_CHECKOUT_PATH}" >/dev/null

  local args=()
  local force_zero_exit="true" # by default this plugin never fails
  if plugin_read_list_into_result BUILDKITE_PLUGIN_CODECOV_ARGS ; then
    for arg in "${result[@]}" ; do
      args+=("${arg}")
      if [[ "${arg}" == "-Z" ]]; then
        force_zero_exit="false"
      fi
    done
  fi

  local ci_env
  ci_env=$(bash ${DIR}/codecov-bash/env)

  set +e
  local exit_code
  docker run \
      $ci_env \
      --label "com.buildkite.job-id=${BUILDKITE_JOB_ID}" \
      --workdir=/workdir \
      --volume=$(pwd):/workdir \
      --volume=${DIR}/codecov-bash:/codecov \
      -it \
      --rm \
      buildpack-deps:jessie-scm \
      bash -c "bash /codecov/bash ${args[*]:-}"
  exit_code="$?"
  set -e
  popd >/dev/null
  rm -r ${DIR}/codecov-bash

  if [[ "${force_zero_exit}" != "true" ]]; then
    exit "${exit_code}"
  fi
}

main "$@"
